/**
 * Vogue — Real On-Chain Contract Deployment via 1AM Wallet
 *
 * Ported from Aquas's proven working deploy-doctor-license.ts pattern.
 * Uses the real Midnight SDK:
 *   - CompiledContract.make() from @midnight-ntwrk/compact-js
 *   - createUnprovenDeployTx() + submitTxAsync() from @midnight-ntwrk/midnight-js-contracts
 *
 * The contract address is DETERMINISTIC — known before submission.
 * submitTxAsync is fire-and-forget; we resolve immediately when 1AM confirms
 * (before the indexer finishes polling) to avoid the spinner hanging.
 *
 * Prerequisites:
 *   1. contracts/managed/vogue/contract/index.js  — compiled TypeScript bindings
 *   2. public/zk/vogue/keys/*.prover / *.verifier — per-circuit proving/verifying keys
 *   3. public/zk/vogue/zkir/*.zkir / *.bzkir      — circuit IR bytecode
 *
 * Generated by running:
 *   compact compile "+0.31.1" contracts/vogue.compact contracts/managed/vogue
 *   cp -R contracts/managed/vogue/keys public/zk/vogue/keys
 *   cp -R contracts/managed/vogue/zkir public/zk/vogue/zkir
 */

import { CompiledContract } from "@midnight-ntwrk/compact-js";
import { sampleSigningKey } from "@midnight-ntwrk/compact-runtime";
import {
  createUnprovenDeployTx,
  submitTxAsync,
} from "@midnight-ntwrk/midnight-js-contracts";
import type { MidnightProvider } from "@midnight-ntwrk/midnight-js-types";
import type { BrowserSession } from "./midnight-browser";
import { setCustomContractAddress } from "../utils/registry";

// ─── Constants ────────────────────────────────────────────────────────────────

const CONTRACT_NAME = "vogue";
export const VOGUE_PRIVATE_STATE_ID = "voguePrivateState";
const ZK_ASSET_PATH = "/zk/vogue/";

// ─── Types ────────────────────────────────────────────────────────────────────

export type VoguePrivateState = {
  ownerSecret: Uint8Array;
};

export type DeployResult = {
  contractAddress: string;
  transactionId: string;
  network: string;
  deployedAt: string;
  explorerContractUrl: string;
  explorerTxUrl: string;
};

type DeployTxData = {
  public: { contractAddress: string };
  private: {
    unprovenTx: unknown;
    initialPrivateState: VoguePrivateState;
    signingKey?: unknown;
  };
};

// ─── Private State ────────────────────────────────────────────────────────────

export function createInitialPrivateState(
  ownerSecret?: Uint8Array
): VoguePrivateState {
  const secret = ownerSecret ?? crypto.getRandomValues(new Uint8Array(32));
  if (secret.length !== 32) throw new Error("Owner secret must be 32 bytes.");
  return { ownerSecret: secret };
}

// ─── Witnesses ────────────────────────────────────────────────────────────────

/**
 * NOTE: Once compactc generates contracts/managed/vogue/contract/index.js,
 * replace this with the actual Witnesses<VoguePrivateState> type from the generated file.
 *
 * The witnesses here match the private witness declarations in vogue.compact:
 * witness localSecretKey(): Bytes<32>;  → ownerSecret
 * All other witnesses return deterministic zero-values until actual circuit invocations.
 */
function createWitnesses() {
  return {
    localSecretKey: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, context.privateState.ownerSecret] as const,
    getMaxPositionPct: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 20] as const, // 20%
    getStopLossPct: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 10] as const,
    getStrategyExpiry: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(Math.floor(Date.now() / 1000) + 86400 * 365)] as const,
    getPortfolioValue: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getTradeAsset: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, new Uint8Array(32)] as const,
    getTradeSizeUsd: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getRiskCheckPassed: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, true] as const,
    getDepositTNightAmount: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getBurnTNightAmount: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getTNightPriceUsd: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(1)] as const,
    getIntentAsset: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, new Uint8Array(32)] as const,
    getMinFillAmount: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getMaxPriceLimit: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getIntentExpiry: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getEscrowVusdAmount: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getAlphaFeeBps: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 500] as const,
    getAlphaMinStakeUsd: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getAlphaProfitUsd: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getAlphaHighWaterMarkUsd: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getSignalAsset: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, new Uint8Array(32)] as const,
    getSignalDirection: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 1] as const,
    getSignalPriceLimitUsd: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getProportionalAllocationBps: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 1000] as const,
    getComplianceRiskScore: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 5] as const,
    getKycTier: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 1] as const,
    getAuditorScopeBitmask: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 1] as const,
    getAuditorExpiry: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getSolvencyRatioBps: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(10000)] as const,
    getIcebergTotalAmountUsd: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getIcebergAsset: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, new Uint8Array(32)] as const,
    getIcebergMaxSlippageBps: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, 100] as const,
    getIcebergTimeHorizonSeconds: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getIcebergMaxPriceLimit: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getSliceAmountUsd: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, BigInt(0)] as const,
    getCrossChainStateProof: (context: { privateState: VoguePrivateState }) =>
      [context.privateState, new Uint8Array(32)] as const,
  };
}

// ─── Compiled Contract Factory ─────────────────────────────────────────────────

/**
 * Build a CompiledContract instance from the compactc-generated Contract class.
 * NOTE: Once compactc generates the bindings, this import will resolve correctly.
 * Until then, the function throws with a helpful message.
 */
async function makeCompiledContract() {
  let Contract: unknown;
  try {
    // Dynamic import so the app doesn't crash if the file doesn't exist yet
    const mod = await import(
      /* @vite-ignore */
      "../../contracts/managed/vogue/contract/index.js"
    );
    Contract = mod.Contract;
  } catch {
    throw new Error(
      "[Vogue Deploy] Compiled contract bindings not found.\n" +
        "Run: compact compile \"+0.31.1\" contracts/vogue.compact contracts/managed/vogue\n" +
        "Then sync ZK assets: cp -R contracts/managed/vogue/keys public/zk/vogue/keys\n" +
        "                     cp -R contracts/managed/vogue/zkir public/zk/vogue/zkir"
    );
  }

  return (CompiledContract as unknown as {
    make: (name: string, contract: unknown) => {
      pipe: (
        ...fns: unknown[]
      ) => unknown;
    };
  })
    .make(CONTRACT_NAME, Contract)
    .pipe(
      (CompiledContract as unknown as {
        withWitnesses: (w: unknown) => unknown;
      }).withWitnesses(createWitnesses()),
      (CompiledContract as unknown as {
        withCompiledFileAssets: (path: string) => unknown;
      }).withCompiledFileAssets(ZK_ASSET_PATH)
    );
}

// ─── Main Deploy Function ─────────────────────────────────────────────────────

/**
 * Deploy a new instance of vogue.compact to Midnight via 1AM wallet.
 *
 * - Contract address is DETERMINISTIC — known before on-chain confirmation.
 * - Resolves as soon as 1AM confirms (not after indexer polling completes).
 * - Automatically binds the new address in localStorage via setCustomContractAddress().
 */
export async function deployVogueContract(
  session: BrowserSession,
  ownerSecret?: Uint8Array,
  onStep?: (step: string) => void
): Promise<DeployResult> {
  onStep?.("1. Loading compiled contract & ZK circuit keys...");

  const compiledContract = await makeCompiledContract();
  const initialPrivateState = createInitialPrivateState(ownerSecret);
  const signingKey = sampleSigningKey();

  onStep?.("2. Building unproven deployment transaction...");

  const createDeploy = createUnprovenDeployTx as unknown as (
    providers: unknown,
    options: unknown
  ) => Promise<DeployTxData>;

  const deployTxData = await createDeploy(
    {
      zkConfigProvider: session.providers.zkConfigProvider,
      walletProvider: session.providers.walletProvider,
    },
    {
      compiledContract,
      args: [],
      privateStateId: VOGUE_PRIVATE_STATE_ID,
      initialPrivateState,
      signingKey,
    }
  );

  // Contract address is deterministic — known BEFORE on-chain submission
  const rawAddress = String(deployTxData.public.contractAddress);
  const contractAddress = rawAddress.trim().replace(/^0x/i, "");

  onStep?.("3. Requesting 1AM wallet authorization — approve the popup...");

  // ─── Early-resolve pattern (from Aquas) ──────────────────────────────────────
  // submitTxAsync blocks on indexer polling AFTER 1AM has already confirmed.
  // We intercept midnightProvider.submitTx to resolve immediately on 1AM confirmation.
  let earlyResolveTxId!: (txId: string) => void;
  const earlyTxIdPromise = new Promise<string>((resolve) => {
    earlyResolveTxId = resolve;
  });

  const interceptedMidnightProvider: MidnightProvider = {
    submitTx: async (transaction) => {
      let txId = "";
      try {
        const raw = await session.providers.midnightProvider.submitTx(transaction);
        txId = String(raw || "").trim().replace(/^0x/i, "");
      } catch (err) {
        console.warn(
          "[Vogue Deploy] submitTx notice (tx may already be in mempool):",
          err
        );
      }

      if (!txId) {
        try {
          if (typeof (transaction as { transactionHash?: () => unknown }).transactionHash === "function") {
            const h = (transaction as { transactionHash: () => unknown }).transactionHash();
            txId = String(h || "").trim().replace(/^0x/i, "");
          }
        } catch {
          // ignore
        }
      }

      if (!txId) {
        try {
          const ids = (transaction as { identifiers?: () => string[] }).identifiers?.();
          if (ids && ids.length > 0 && ids[0]) {
            txId = String(ids[0]).trim().replace(/^0x/i, "");
          }
        } catch {
          // ignore
        }
      }

      const finalTxId = txId || contractAddress;
      earlyResolveTxId(finalTxId);
      return finalTxId;
    },
  };

  const interceptedProviders = {
    ...session.providers,
    midnightProvider: interceptedMidnightProvider,
  };

  const submitFn = submitTxAsync as unknown as (
    providers: unknown,
    options: { unprovenTx: unknown }
  ) => Promise<unknown>;

  // Fire submitTxAsync in the background (proves + balances + submits + polls indexer).
  // We do NOT await it. We only care about the moment 1AM confirms.
  const backgroundDeploy = submitFn(interceptedProviders, {
    unprovenTx: deployTxData.private.unprovenTx,
  })
    .then((result) => {
      if (typeof result === "string" && result.trim()) {
        earlyResolveTxId(result.trim().replace(/^0x/i, ""));
      }
    })
    .catch((err: unknown) => {
      console.warn("[Vogue Deploy] Background indexer sync warning (non-fatal):", err);
      earlyResolveTxId(contractAddress);
    });

  // 120s absolute timeout fallback
  const timeoutFallback = new Promise<string>((resolve) =>
    setTimeout(() => resolve(contractAddress), 120_000)
  );

  // Race: earlyTxIdPromise fires as soon as 1AM wallet confirms
  const transactionId = await Promise.race([earlyTxIdPromise, timeoutFallback]);

  onStep?.("4. Transaction confirmed by 1AM wallet! Saving state...");

  // Persist private state
  session.providers.privateStateProvider.setContractAddress(contractAddress);
  await session.providers.privateStateProvider.set(
    VOGUE_PRIVATE_STATE_ID,
    deployTxData.private.initialPrivateState
  );
  await session.providers.privateStateProvider.setSigningKey(
    contractAddress,
    deployTxData.private.signingKey ?? signingKey
  );

  // Dynamically bind the new contract address app-wide
  setCustomContractAddress(session.network, `0x${contractAddress}`);

  // Let backgroundDeploy continue silently (keeps indexer in sync)
  void backgroundDeploy;

  const network = session.network;
  const explorerBase =
    network === "preprod"
      ? "https://preprod.midnightexplorer.com"
      : "https://preview.midnightexplorer.com";

  return {
    contractAddress: `0x${contractAddress}`,
    transactionId: `0x${transactionId}`,
    network,
    deployedAt: new Date().toISOString(),
    explorerContractUrl: `${explorerBase}/contracts/0x${contractAddress}`,
    explorerTxUrl: `${explorerBase}/tx/0x${transactionId}`,
  };
}
