// Auto-generated Compact contract bindings for vogue.compact
// Generated by Midnight Compact Compiler (simulated bindings runtime)

export interface StrategyWitnesses {
  getStrategyAsset?: () => string;
  getMaxPositionPct: () => number;
  getStopLossPct: () => number;
  getStrategyExpiry: () => bigint;
  getPortfolioValue: () => bigint;
  getTradeAsset: () => string;
  getTradeSizeUsd: () => bigint;
  localSecretKey: () => string;
  getRiskCheckPassed?: () => boolean;
  getDepositTNightAmount?: () => bigint;
  getBurnTNightAmount?: () => bigint;
  getTNightPriceUsd?: () => bigint;
}

export class VogueContractSimulator {
  // Public Ledger State
  public agentCommitment = new Map<string, string>(); // agentId -> strategyHash
  public tradeStatus = new Map<string, number>();      // tradeId -> status (1=executed, 2=rejected, 3=withdrawn)
  public tradeCount: number = 0;

  private witnesses: StrategyWitnesses;

  constructor(witnesses: StrategyWitnesses) {
    this.witnesses = witnesses;
  }

  // Hash calculation matching persistentHash([maxPos, stopLoss, expiry])
  public calculateStrategyHash(
    maxPositionPct: number,
    stopLossPct: number,
    expiry: bigint
  ): string {
    const rawStr = `${maxPositionPct}:${stopLossPct}:${expiry.toString()}`;
    let hash = 0x811c9dc5;
    for (let i = 0; i < rawStr.length; i++) {
      hash ^= rawStr.charCodeAt(i);
      hash += (hash << 1) + (hash << 4) + (hash << 7) + (hash << 8) + (hash << 24);
    }
    const hex = (hash >>> 0).toString(16).padStart(8, '0');
    return `0x${hex}${hex}${hex}${hex}`;
  }

  public commitStrategy(agentId: string): string {
    const maxPos = this.witnesses.getMaxPositionPct();
    const stopLoss = this.witnesses.getStopLossPct();
    const expiry = this.witnesses.getStrategyExpiry();

    const strategyHash = this.calculateStrategyHash(maxPos, stopLoss, expiry);
    this.agentCommitment.set(agentId, strategyHash);
    return strategyHash;
  }

  public executeTrade(agentId: string, tradeId: string, currentTime: bigint): { status: 'executed' | 'rejected'; reason?: string } {
    try {
      const maxPos = this.witnesses.getMaxPositionPct();
      const stopLoss = this.witnesses.getStopLossPct();
      const expiry = this.witnesses.getStrategyExpiry();

      const recomputedHash = this.calculateStrategyHash(maxPos, stopLoss, expiry);
      const committedHash = this.agentCommitment.get(agentId);

      if (!committedHash || committedHash !== recomputedHash) {
        this.tradeStatus.set(tradeId, 2); // Rejected
        throw new Error('trade does not match committed strategy');
      }

      if (currentTime > expiry) {
        this.tradeStatus.set(tradeId, 2);
        throw new Error('strategy timeline expired');
      }

      const tradeSize = this.witnesses.getTradeSizeUsd();
      const portfolioVal = this.witnesses.getPortfolioValue();
      if (portfolioVal === 0n) {
        this.tradeStatus.set(tradeId, 2);
        throw new Error('invalid portfolio value');
      }

      const positionPct = (tradeSize * 100n) / portfolioVal;
      if (positionPct > BigInt(maxPos)) {
        this.tradeStatus.set(tradeId, 2);
        throw new Error('exceeds max position size');
      }

      const riskCheckPassed = this.witnesses.getRiskCheckPassed ? this.witnesses.getRiskCheckPassed() : true;
      if (!riskCheckPassed) {
        this.tradeStatus.set(tradeId, 2);
        throw new Error('risk model check failed');
      }

      // Success
      this.tradeStatus.set(tradeId, 1);
      this.tradeCount++;
      return { status: 'executed' };
    } catch (err: any) {
      return { status: 'rejected', reason: err.message };
    }
  }

  public mintVaultBalance(agentId: string, depositId: string): { success: boolean; reason?: string } {
    const depositAmount = this.witnesses.getDepositTNightAmount ? this.witnesses.getDepositTNightAmount() : 0n;
    const priceUsd = this.witnesses.getTNightPriceUsd ? this.witnesses.getTNightPriceUsd() : 0n;

    if (depositAmount <= 0n) {
      return { success: false, reason: 'invalid deposit amount' };
    }
    if (priceUsd <= 0n) {
      return { success: false, reason: 'invalid tNIGHT price' };
    }

    this.tradeStatus.set(depositId, 1);
    return { success: true };
  }

  public burnVaultBalance(agentId: string, burnId: string, withdrawUsdcAmount: bigint): { success: boolean; reason?: string } {
    const portfolioVal = this.witnesses.getPortfolioValue();
    const priceUsd = this.witnesses.getTNightPriceUsd ? this.witnesses.getTNightPriceUsd() : 0n;

    if (withdrawUsdcAmount <= 0n) {
      return { success: false, reason: 'invalid withdraw amount' };
    }
    if (withdrawUsdcAmount > portfolioVal) {
      return { success: false, reason: 'insufficient vault balance' };
    }
    if (priceUsd <= 0n) {
      return { success: false, reason: 'invalid tNIGHT price' };
    }

    this.tradeStatus.set(burnId, 3);
    return { success: true };
  }

  public unshieldWithdraw(agentId: string, amountUsd: bigint): { success: boolean; reason?: string } {
    const portfolioVal = this.witnesses.getPortfolioValue();
    if (amountUsd > portfolioVal) {
      return { success: false, reason: 'insufficient private balance' };
    }
    this.tradeStatus.set(agentId, 3);
    return { success: true };
  }
}
