import React, { useRef, useState, useEffect } from 'react';
import { Shield, Activity, Zap, Cpu, Lock, Network, Menu, X } from 'lucide-react';
import '../prisma-globals.css';
import '../prisma-landing.css';

const NAV_LINKS = [
  { label: 'Features', href: '#features' },
  { label: 'How it Works', href: '#workflow' },
];

const STATS = [
  { value: '100%', label: 'Shielded', note: 'Private state on Midnight' },
  { value: '<3s', label: 'Proof Time', note: 'Client-side ZK proving' },
  { value: '0%', label: 'Data Leak', note: 'Zero-knowledge guarantees' },
];

const FEATURES = [
  {
    icon: Shield,
    title: 'Shielded Vault (vUSD)',
    desc: 'Deposit, trade, and withdraw without linking your public wallet address to trading history.',
  },
  {
    icon: Zap,
    title: 'Client-Side Execution',
    desc: 'Zero-Knowledge proofs are generated and verified locally in the browser before being broadcasted.',
  },
  {
    icon: Activity,
    title: 'Gemini Technical Signals',
    desc: 'Live cryptocurrency price feeds and automated technical analysis generated by Gemini 2.5 Flash.',
  },
  {
    icon: Cpu,
    title: 'EZKL Risk Verification',
    desc: 'Machine learning constraints mathematically enforce risk limits before executing the trade.',
  },
  {
    icon: Network,
    title: 'Immutable Ledger',
    desc: 'Every shielded trade execution is cryptographically recorded on the Midnight blockchain.',
  },
  {
    icon: Lock,
    title: 'Zero Address Linkability',
    desc: 'Full separation between your public transaction history and your active trading positions.',
  },
];

const WORKFLOW_STEPS = [
  {
    n: '01',
    title: 'Synthesize Strategy',
    desc: 'Configure your trade using natural language. Gemini 2.5 Flash constructs high-frequency parameters.',
  },
  {
    n: '02',
    title: 'EZKL Verification',
    desc: 'A machine learning model ensures the generated strategy falls strictly within safety bounds.',
  },
  {
    n: '03',
    title: 'Generate ZK Proof',
    desc: 'Our Compact circuit compiles a zero-knowledge proof client-side, validating all constraints without server exposure.',
  },
  {
    n: '04',
    title: 'Submit to Midnight',
    desc: 'The shielded transaction is broadcast. Validators verify the proof and execute the dark pool swap.',
  },
];

export const LandingPage = ({ onConnectWallet, onEnterDashboard, walletConnected, walletAddress }) => {
  const videoRef = useRef(null);
  const [videoReady, setVideoReady] = useState(false);
  const [navOpen, setNavOpen] = useState(false);

  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    const p = v.play();
    if (p?.catch) p.catch(() => {});
  }, []);

  return (
    <div className="lp-root">
      {/* ── STICKY VIDEO BACKGROUND ── */}
      <div className="lp-bg" aria-hidden="true">
        <video
          ref={videoRef}
          className={videoReady ? 'ready' : ''}
          src="/hero.mp4"
          autoPlay muted loop playsInline preload="auto"
          onCanPlay={() => setVideoReady(true)}
        />
        <div className="lp-bg__scrim" />
      </div>

      {/* ── LIQUID GLASS NAVBAR ── */}
      <header className="nav">
        <div className="nav__pill">
          <a className="nav__brand flex items-center gap-2" href="/">
            <img src="/vogue-logo.svg" className="w-5 h-5" alt="Vogue" />
            <span>Vogue</span>
            <span className="nav__badge">Beta</span>
          </a>

          <nav className="nav__rail" aria-label="Primary">
            {NAV_LINKS.map(l => (
              <a key={l.label} href={l.href}>{l.label}</a>
            ))}
          </nav>

          <div className="nav__actions">
            <button className="btn-glass btn-glass--primary cursor-pointer" onClick={walletConnected ? onEnterDashboard : onConnectWallet}>
              {walletConnected ? 'Dashboard →' : 'Get Started →'}
            </button>
          </div>

          <button
            className="nav__toggle"
            onClick={() => setNavOpen(!navOpen)}
          >
            {navOpen ? <X size={20} /> : <Menu size={20} />}
          </button>
        </div>
      </header>

      {/* HERO */}
      <section className="hero" id="top">
        <div className="hero__body shell">
          <div className="hero__pill-tag">
            <span className="hero__dot" />
            <span>Midnight Network · Zero-Knowledge Infrastructure</span>
          </div>

          <h1 className="hero__title">
            Shielded Trades &<br />
            <em>AI Synthesis</em><br />
            at Enterprise Scale.
          </h1>

          <p className="hero__sub">
            Vogue brings cryptographic zero-knowledge proofs to algorithmic trading.
            Execute private, verifiable market moves — without leaking your alpha.
          </p>

          <div className="hero__actions">
            <button className="btn-glass btn-glass--primary cursor-pointer" onClick={walletConnected ? onEnterDashboard : onConnectWallet}>
              {walletConnected ? 'Launch Dashboard →' : 'Connect 1AM Wallet →'}
            </button>
            <a className="btn-glass" href="#workflow">
              How it Works
            </a>
          </div>
        </div>

        <div className="hero__foot shell">
          <div className="hero__note">
            <h3>Zero-Knowledge Privacy</h3>
            <p>Every trade is cryptographically verified on Midnight without revealing amounts or strategies to the network.</p>
          </div>

          <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.8rem', fontWeight: 300, paddingBottom: '6px', textAlign: 'center' }}>
            Proof-verified. Never exposed. Always shielded.
          </p>

          <div style={{ display: 'flex', gap: '16px' }}>
            {STATS.map(s => (
              <div key={s.value} className="stat-card">
                <strong>{s.value}</strong>
                <span>{s.label}</span>
                <span style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.35)', marginTop: '4px' }}>{s.note}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="lp-section shell" id="features">
        <div className="section__header">
          <div className="section__eyebrow">Core Capabilities</div>
          <h2 className="section__title">Built for the Shielded Economy</h2>
          <p className="section__desc">
            Every feature of Vogue is designed around the principle that your trading edge should be verifiable without being visible.
          </p>
        </div>

        <div className="features-grid">
          {FEATURES.map(f => {
            const Icon = f.icon;
            return (
              <div key={f.title} className="feat-card">
                <div className="feat-card__icon">
                  <Icon className="w-5 h-5" />
                </div>
                <h3 className="feat-card__title">{f.title}</h3>
                <p className="feat-card__desc">{f.desc}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="lp-section shell" id="workflow">
        <div className="section__header">
          <div className="section__eyebrow">Protocol Flow</div>
          <h2 className="section__title">From Prompt to Execution</h2>
        </div>

        <div className="workflow-split">
          <ul className="workflow__steps">
            {WORKFLOW_STEPS.map(s => (
              <li key={s.n} className="workflow__step">
                <div className="step-num">{s.n}</div>
                <div className="step-body">
                  <strong>{s.title}</strong>
                  <p>{s.desc}</p>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="site-footer" style={{ padding: '40px 0', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
        <div className="shell">
          <div className="footer-top">
            <div className="footer-brand">
              <div className="footer-brand__name flex items-center gap-2 font-bold text-white mb-2">
                <img src="/vogue-logo.svg" className="w-6 h-6 grayscale opacity-70" />
                Vogue Trade
              </div>
              <p className="footer-brand__desc text-gray-400 text-sm max-w-sm">
                Zero-knowledge trading infrastructure built natively on the Midnight Network. Private, verifiable, immutable.
              </p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};
export default LandingPage;
